import type { Fixture, Team } from './types'

export const teams: Team[] = [
  {
    code: 'RCB',
    name: 'Royal Challengers Bengaluru',
    short: 'Royal Challengers',
    played: 12,
    won: 8,
    lost: 4,
    ties: 0,
    noResult: 0,
    points: 16,
    nrr: 1.053,
    color: '#c8102e',
    ink: '#fef4f5',
  },
  {
    code: 'GT',
    name: 'Gujarat Titans',
    short: 'Titans',
    played: 12,
    won: 8,
    lost: 4,
    ties: 0,
    noResult: 0,
    points: 16,
    nrr: 0.551,
    color: '#1b2133',
    ink: '#eef1f8',
  },
  {
    code: 'SRH',
    name: 'Sunrisers Hyderabad',
    short: 'Sunrisers',
    played: 12,
    won: 7,
    lost: 5,
    ties: 0,
    noResult: 0,
    points: 14,
    nrr: 0.331,
    color: '#f26b21',
    ink: '#1a0d05',
  },
  {
    code: 'PBKS',
    name: 'Punjab Kings',
    short: 'Kings',
    played: 12,
    won: 6,
    lost: 5,
    ties: 0,
    noResult: 1,
    points: 13,
    nrr: 0.355,
    color: '#d71920',
    ink: '#fdf3f3',
  },
  {
    code: 'CSK',
    name: 'Chennai Super Kings',
    short: 'Super Kings',
    played: 11,
    won: 6,
    lost: 5,
    ties: 0,
    noResult: 0,
    points: 12,
    nrr: 0.185,
    color: '#f7c600',
    ink: '#1a1500',
  },
  {
    code: 'RR',
    name: 'Rajasthan Royals',
    short: 'Royals',
    played: 11,
    won: 6,
    lost: 5,
    ties: 0,
    noResult: 0,
    points: 12,
    nrr: 0.082,
    color: '#ea1a85',
    ink: '#fef3f8',
  },
  {
    code: 'DC',
    name: 'Delhi Capitals',
    short: 'Capitals',
    played: 12,
    won: 5,
    lost: 7,
    ties: 0,
    noResult: 0,
    points: 10,
    nrr: -0.993,
    color: '#17479e',
    ink: '#eef3fc',
  },
  {
    code: 'KKR',
    name: 'Kolkata Knight Riders',
    short: 'Knight Riders',
    played: 11,
    won: 4,
    lost: 6,
    ties: 0,
    noResult: 1,
    points: 9,
    nrr: -0.198,
    color: '#3b215d',
    ink: '#f4eefc',
  },
  {
    code: 'MI',
    name: 'Mumbai Indians',
    short: 'Indians',
    played: 12,
    won: 4,
    lost: 8,
    ties: 0,
    noResult: 0,
    points: 8,
    nrr: -0.504,
    color: '#006cb7',
    ink: '#eef4fb',
  },
  {
    code: 'LSG',
    name: 'Lucknow Super Giants',
    short: 'Super Giants',
    played: 11,
    won: 3,
    lost: 8,
    ties: 0,
    noResult: 0,
    points: 6,
    nrr: -0.907,
    color: '#00a9e0',
    ink: '#02212c',
  },
]

export const fixtures: Fixture[] = [
  { id: 59, date: 'May 15, 2026', venue: 'Lucknow', home: 'LSG', away: 'CSK' },
  { id: 60, date: 'May 16, 2026', venue: 'Kolkata', home: 'KKR', away: 'GT' },
  { id: 61, date: 'May 17, 2026', venue: 'Dharamsala', home: 'PBKS', away: 'RCB' },
  { id: 62, date: 'May 17, 2026', venue: 'Delhi', home: 'DC', away: 'RR' },
  { id: 63, date: 'May 18, 2026', venue: 'Chennai', home: 'CSK', away: 'SRH' },
  { id: 64, date: 'May 19, 2026', venue: 'Jaipur', home: 'RR', away: 'LSG' },
  { id: 65, date: 'May 20, 2026', venue: 'Kolkata', home: 'KKR', away: 'MI' },
  { id: 66, date: 'May 21, 2026', venue: 'Ahmedabad', home: 'GT', away: 'CSK' },
  { id: 67, date: 'May 22, 2026', venue: 'Hyderabad', home: 'SRH', away: 'RCB' },
  { id: 68, date: 'May 23, 2026', venue: 'Lucknow', home: 'LSG', away: 'PBKS' },
  { id: 69, date: 'May 24, 2026', venue: 'Mumbai', home: 'MI', away: 'RR' },
  { id: 70, date: 'May 24, 2026', venue: 'Kolkata', home: 'KKR', away: 'DC' },
]

export const sources = [
  {
    label: 'NDTV Sports — points table after Match 58',
    url: 'https://sports.ndtv.com/ipl-2026/points-table',
  },
  {
    label: 'Indian Express — standings cross-check',
    url: 'https://indianexpress.com/section/sports/ipl/points-table/',
  },
  {
    label: 'myKhel — completed results through Match 58',
    url: 'https://www.mykhel.com/cricket/ipl-schedule-results-s4/',
  },
]

export const lastUpdated = 'After Match 58, fetched May 15, 2026'

export const teamOrder = new Map(teams.map((team, index) => [team.code, index]))
export const teamByCode = new Map(teams.map((team) => [team.code, team]))
export const allTeamCodes = teams.map((team) => team.code)
