import type { Fixture, Team } from './types'

export const teams: Team[] = [
  {
    code: 'RCB',
    name: 'Royal Challengers Bengaluru',
    short: 'Royal Challengers',
    played: 13,
    won: 9,
    lost: 4,
    ties: 0,
    noResult: 0,
    points: 18,
    nrr: 1.065,
    color: '#c8102e',
    ink: '#fef4f5',
  },
  {
    code: 'GT',
    name: 'Gujarat Titans',
    short: 'Titans',
    played: 13,
    won: 8,
    lost: 5,
    ties: 0,
    noResult: 0,
    points: 16,
    nrr: 0.4,
    color: '#1b2133',
    ink: '#eef1f8',
  },
  {
    code: 'SRH',
    name: 'Sunrisers Hyderabad',
    short: 'Sunrisers',
    played: 13,
    won: 8,
    lost: 5,
    ties: 0,
    noResult: 0,
    points: 16,
    nrr: 0.35,
    color: '#f26b21',
    ink: '#1a0d05',
  },
  {
    code: 'PBKS',
    name: 'Punjab Kings',
    short: 'Kings',
    played: 13,
    won: 6,
    lost: 6,
    ties: 0,
    noResult: 1,
    points: 13,
    nrr: 0.227,
    color: '#d71920',
    ink: '#fdf3f3',
  },
  {
    code: 'RR',
    name: 'Rajasthan Royals',
    short: 'Royals',
    played: 13,
    won: 7,
    lost: 6,
    ties: 0,
    noResult: 0,
    points: 14,
    nrr: 0.083,
    color: '#ea1a85',
    ink: '#fef3f8',
  },
  {
    code: 'CSK',
    name: 'Chennai Super Kings',
    short: 'Super Kings',
    played: 13,
    won: 6,
    lost: 7,
    ties: 0,
    noResult: 0,
    points: 12,
    nrr: -0.016,
    color: '#f7c600',
    ink: '#1a1500',
  },
  {
    code: 'DC',
    name: 'Delhi Capitals',
    short: 'Capitals',
    played: 13,
    won: 6,
    lost: 7,
    ties: 0,
    noResult: 0,
    points: 12,
    nrr: -0.871,
    color: '#17479e',
    ink: '#eef3fc',
  },
  {
    code: 'KKR',
    name: 'Kolkata Knight Riders',
    short: 'Knight Riders',
    played: 12,
    won: 5,
    lost: 6,
    ties: 0,
    noResult: 1,
    points: 11,
    nrr: -0.038,
    color: '#3b215d',
    ink: '#f4eefc',
  },
  {
    code: 'MI',
    name: 'Mumbai Indians',
    short: 'Indians',
    played: 12,
    won: 4,
    lost: 8,
    ties: 0,
    noResult: 0,
    points: 8,
    nrr: -0.504,
    color: '#006cb7',
    ink: '#eef4fb',
  },
  {
    code: 'LSG',
    name: 'Lucknow Super Giants',
    short: 'Super Giants',
    played: 13,
    won: 4,
    lost: 9,
    ties: 0,
    noResult: 0,
    points: 8,
    nrr: -0.702,
    color: '#00a9e0',
    ink: '#02212c',
  },
]

export const fixtures: Fixture[] = [
  { id: 65, date: 'May 20, 2026', venue: 'Kolkata', home: 'KKR', away: 'MI' },
  { id: 66, date: 'May 21, 2026', venue: 'Ahmedabad', home: 'GT', away: 'CSK' },
  { id: 67, date: 'May 22, 2026', venue: 'Hyderabad', home: 'SRH', away: 'RCB' },
  { id: 68, date: 'May 23, 2026', venue: 'Lucknow', home: 'LSG', away: 'PBKS' },
  { id: 69, date: 'May 24, 2026', venue: 'Mumbai', home: 'MI', away: 'RR' },
  { id: 70, date: 'May 24, 2026', venue: 'Kolkata', home: 'KKR', away: 'DC' },
]

export const sources = [
  {
    label: 'Indian Express — points table as of May 19, 2026, 11:28 PM IST',
    url: 'https://indianexpress.com/section/sports/ipl/points-table/',
  },
  {
    label: 'NDTV Sports — points table and fixtures after Match 64',
    url: 'https://sports.ndtv.com/ipl-2026/points-table',
  },
  {
    label: 'Wisden — Match 64 result cross-check',
    url: 'https://www.wisden.com/series/ipl-2026/cricket-news/ipl-2026-points-table-after-rr-vs-lsg-latest-standings-and-net-run-rate-after-rajasthan-beat-lucknow',
  },
  {
    label: 'IPL.com — Match 64 scorecard and table',
    url: 'https://www.ipl.com/matches/indian-premier-league-129908/rajasthan-royals-vs-lucknow-super-giants-96021',
  },
]

export const lastUpdated = 'After Match 64, fetched May 20, 2026'

export const teamOrder = new Map(teams.map((team, index) => [team.code, index]))
export const teamByCode = new Map(teams.map((team) => [team.code, team]))
export const allTeamCodes = teams.map((team) => team.code)
